100mslive/web-sdks

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
> feat: add issue templates

- packages/roomkit-react/src/Prebuilt/components/Notifications/PermissionErrorModal.tsx
- packages/roomkit-react/src/Sheet/Sheet.tsx
> fix: ui freeze on mweb in bring on stage flow

- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
- Added a slider for adjusting the blur intensity
> fix: slider for blur intensity

- packages/roomkit-react/src/Prebuilt/components/RoleChangeRequest/RequestPrompt.tsx
- packages/roomkit-react/src/Prebuilt/components/RoleChangeRequest/RoleChangeRequestModal.tsx
> fix: disable mid call preview toggles until permissions are granted

- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
- Poll start toast should remain visible until the peer interacts with it or until the activity ends
> fix: keep poll toast open until interaction for hls viewer

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
> feat: auto select bluetooth/speaker as output in mweb

- packages/roomkit-react/src/Button/Button.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/LeaderboardEntry.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/LeaderboardSummary.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/PeerParticipationSummary.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/QuestionCard.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/StandardVoting.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/TimedVoting.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/Voting.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/common/MultipleChoiceOptions.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/common/SingleChoiceOptions.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/common/StatusIndicator.tsx
> feat: add duration metric to responses, leaderboard and participation summary

- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
- packages/hms-virtual-background/src/HMSVBPlugin.ts
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBHandler.tsx
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
- Access the blur intensity value from the VB object on rerender
> fix: persist blur intensity in vb slider

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
> fix: handle wired headphone in auto output selection

- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/Voting.tsx
- Show end poll/quiz button if the peer has the permissions to create polls
> fix: show end button if poll write permissions are present

- packages/roomkit-react/src/Prebuilt/components/TileMenu/TileMenuContent.tsx
> fix: remote audio volume

- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
> fix: black tile when vb is enabled in preview

- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/QuestionCard.jsx
> fix: scroll only for too many options

- packages/roomkit-react/src/Prebuilt/components/Chat/ChatActions.tsx
- packages/roomkit-react/src/Prebuilt/components/Chat/ChatBody.tsx
> fix: message actions close not working

- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBHandler.tsx
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/constants.ts
- VB quality can now be adjusted through the UI
<br />
> feat: expose vb presets, update default

- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/constants.ts
- Remove the quality slider and use a balanced preset
> fix: remove quality slider

- CODEOWNERS
- packages/roomkit-react/package.json
- packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx
- packages/roomkit-react/src/Prebuilt/provider/roomLayoutProvider/hooks/useRoomLayoutScreen.ts
- yarn.lock
> feat: handle skip_preview_screen in preview screen layout

- examples/prebuilt-react-integration/vite.config.js
- packages/hms-video-store/package.json
- packages/hms-video-store/src/media/settings/HMSVideoTrackSettings.ts
- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-video-store/src/sdk/LocalTrackManager.ts
- yarn.lock
> fix: inset tile showing wrong aspect ratio in iOS

- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/TimedVoting.tsx
> fix: show all questions if attempted all

- packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx
> fix: height of chat overlay in mweb

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> fix: height of smaller tiles

- packages/roomkit-react/src/Prebuilt/components/Connection/ConnectionIndicator.tsx
- packages/roomkit-react/src/Prebuilt/components/Connection/connectionQualityUtils.js
> fix: connection quality indicator

- packages/roomkit-react/src/Prebuilt/components/SecondaryTiles.tsx
> fix: pin, spotlight sorting in secondary tiles

- packages/roomkit-react/src/Prebuilt/components/hooks/useFullscreen.js
> feat: make prebuilt fullscreen not the complete page

- packages/roomkit-react/src/Prebuilt/components/Chat/ChatBody.tsx
- packages/roomkit-react/src/Prebuilt/components/Chat/EmptyChat.tsx
- packages/roomkit-react/src/Prebuilt/components/SidePaneTabs.tsx
- packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx
> fix: css for chatbody

- packages/roomkit-react/src/Prebuilt/components/ScreenshareTile.tsx
> fix: screenshare mirroring

- packages/roomkit-react/src/Prebuilt/components/ScreenshareTile.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ScreenshareLayout.tsx
> fix: remove sidebar mode for mweb

- packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx
- packages/roomkit-react/src/Prebuilt/components/Chat/EmptyChat.tsx
- packages/roomkit-react/src/Prebuilt/components/SidePaneTabs.tsx
- packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx
- Horizontal overflow for desktop chat
- Mweb overlay chat gets hidden
> fix: chat body css

- packages/roomkit-react/src/Prebuilt/components/Polls/CreatePollQuiz/PollsQuizMenu.tsx
- Preserve polls attempted by peers with read permission after it ends
> fix: preserve attempted polls

- packages/roomkit-react/src/Prebuilt/components/ScreenshareTile.tsx
> fix: remove layout options when in fullscreen

- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
- packages/hms-video-store/src/session-store/interactivity-center/HMSInteractivityCenter.ts
- packages/roomkit-react/src/Prebuilt/components/Chat/ChatBody.tsx
- packages/roomkit-react/src/Prebuilt/components/Chat/PinnedMessage.tsx
- packages/roomkit-react/src/Prebuilt/components/HMSVideo/VideoProgress.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/CreatePollQuiz/PollsQuizMenu.tsx
- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
> Update publish alpha

- packages/hms-video-store/src/schema/room.ts
- packages/hms-video-store/src/sdk/models/HMSRoom.ts
- packages/hms-video-store/src/signal/init/models.ts
- packages/hms-video-store/src/transport/index.ts
> feat: add hippa flag to room

- packages/hms-video-store/package.json
- packages/hms-video-store/src/analytics/AnalyticsEvent.ts
- packages/hms-video-store/src/analytics/HTTPAnalyticsTransport.ts
- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/sdk/store/Store.ts
- packages/hms-video-store/src/signal/init/init.test.ts
- packages/hms-video-store/src/transport/index.ts
- packages/hms-video-store/src/utils/support.ts
- packages/hms-video-store/src/utils/user-agent.ts
- packages/roomkit-react/src/Prebuilt/common/constants.ts
- yarn.lock
- https://docs.uaparser.js.org/v2/api/ua-parser-js/idata/with-client-hints.html
-
> fix: upgrade ua-parser-js to track correct mac os version

- packages/hms-video-store/src/analytics/stats/BaseStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/PublishStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/SubscribeStatsAnalytics.ts
> fix: timestamps for publisher.stats by creating all tracks/layers samples at once

- examples/prebuilt-react-integration/src/App.jsx
- packages/hms-video-store/src/interfaces/room.ts
- packages/hms-video-store/src/reactive-store/adapter.ts
- packages/hms-video-store/src/schema/room.ts
- packages/hms-video-store/src/sdk/models/HMSRoom.ts
- packages/hms-video-store/src/signal/init/models.ts
- packages/hms-video-store/src/transport/index.ts
- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
> feat: use a flag to enabled noise cancellation

- packages/hms-video-store/src/interfaces/room.ts
- packages/hms-video-store/src/reactive-store/adapter.ts
- packages/hms-video-store/src/schema/room.ts
- packages/hms-video-store/src/sdk/models/HMSRoom.ts
- packages/hms-video-store/src/signal/init/models.ts
- packages/hms-video-store/src/transport/index.ts
> fix: typo in hipaa flag

- packages/hms-video-store/package.json
- packages/hms-video-store/src/analytics/AnalyticsEvent.ts
- packages/hms-video-store/src/analytics/HTTPAnalyticsTransport.ts
- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/sdk/store/Store.ts
- packages/hms-video-store/src/signal/init/init.test.ts
- packages/hms-video-store/src/transport/index.ts
- packages/hms-video-store/src/utils/support.ts
- packages/hms-video-store/src/utils/user-agent.ts
- packages/roomkit-react/src/Prebuilt/common/constants.ts
- yarn.lock
Reverts 100mslive/web-sdks#2543
> Revert "fix: upgrade ua-parser-js to track correct mac os version"

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> fix: content overflow for sidebar on smaller res

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/RoleProminence.tsx
> feat: apply maxtilecount from settings to role prominence

- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
- packages/roomkit-react/src/Prebuilt/components/Connection/TileConnection.tsx
- packages/roomkit-react/src/Prebuilt/components/Preview/PreviewJoin.tsx
> fix: connection quality in preview

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
> feat: add polling for devices when device change not available

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/RoleProminence.tsx
- packages/roomkit-react/src/Prebuilt/components/hooks/useRoleProminencePeers.tsx
> fix: active speaker sorting in role prominence

- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
- packages/roomkit-react/src/Prebuilt/components/Footer/RoleOptions.tsx
> fix: update selected device css, mute all label

- packages/roomkit-react/src/Prebuilt/components/Footer/RoleOptions.tsx
- packages/roomkit-react/src/Prebuilt/components/TileMenu/TileMenuContent.tsx
> fix: page crash for options in hand raise accordion

- packages/roomkit-react/src/Prebuilt/components/AppData/useSidepane.js
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx
> fix: poll close, mweb options crash

- packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx
- packages/roomkit-react/src/Prebuilt/components/EmojiReaction.jsx
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx
> fix: emoji reaction for streaming

- packages/roomkit-react/src/Prebuilt/components/HMSVideo/VideoTime.tsx
> fix: nan timer while buffering

- packages/roomkit-react/src/Prebuilt/components/HMSVideo/HLSQualitySelector.tsx
- packages/roomkit-react/src/Prebuilt/components/Leave/DesktopLeaveRoom.tsx
- packages/roomkit-react/src/Prebuilt/components/Leave/LeaveRoom.tsx
- packages/roomkit-react/src/Prebuilt/components/Leave/MwebLeaveRoom.tsx
- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
- packages/roomkit-react/src/Sheet/Sheet.tsx
> fix: show contriols when in fullscreen

- packages/roomkit-react/src/Prebuilt/components/HMSVideo/VideoProgress.tsx
> fix: show seekbar in iphone

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
> fix: don't log polling device changes to analytics

- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
> fix: polls not opening from notification

- packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx
- packages/roomkit-react/src/Prebuilt/components/Chat/EmptyChat.tsx
> fix: chat ui fixes

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
> revert: polling device change for mweb

- packages/hms-video-store/src/analytics/stats/BaseStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/PublishStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/SubscribeStatsAnalytics.ts
> fix: frozen stats

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ScreenshareLayout.tsx
- packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx
> feat: add test logs to debug screenshare

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> fix: screen peers in sidepane

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> revert: height for video tiles in sidebar

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
- packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx
> fix: remove test logs

- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-virtual-background/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
-  https://github.com/100mslive/web-sdks/issues/2658
-
> feat: add type: 'module' to all packages

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> fix: video tile size when res changes in sidebar

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
> Merge main to dev

- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/jest.config.js
- packages/hms-video-store/package.json
- packages/hms-virtual-background/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> revert: type 'module' as it causing some build issues

- packages/hms-video-store/src/analytics/stats/BaseStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/SubscribeStatsAnalytics.ts
- packages/hms-video-store/src/interfaces/webrtc-stats.ts
> fix: calcuating difference average, av sync and remove unnecessary fields for subscriber stats sample 

- packages/hms-video-store/src/session-store/interactivity-center/HMSInteractivityCenter.ts
- packages/roomkit-react/src/Prebuilt/components/Polls/CreateQuestions/CreateQuestions.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/CreateQuestions/SavedQuestion.tsx
- packages/roomkit-react/src/Prebuilt/components/Polls/common/MultipleChoiceOptions.jsx
- packages/roomkit-react/src/Prebuilt/components/Polls/common/SingleChoiceOptions.jsx
> fix: save correct answers in draft quizzes

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-virtual-background/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-react/src/Prebuilt/components/Footer/ParticipantList.tsx
- packages/roomkit-react/src/Prebuilt/components/Footer/RoleAccordion.tsx
- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
- packages/roomkit-web/package.json
- yarn.lock
> Merge main

- examples/prebuilt-react-integration/src/App.jsx
- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
> feat: add polling for devices when device change not supported

- packages/roomkit-react/src/Prebuilt/components/Footer/ChatToggle.tsx
- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
<br /> chat with count <br />
<br /> Old without chat icon <br />
<br /> new with chat icon in fullscreen  <br />
> fix: chat count in landscape and fullscreen

- packages/roomkit-react/package.json
- packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx
- packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx
- packages/roomkit-react/src/Prebuilt/components/Footer/Footer.tsx
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx
- packages/roomkit-react/src/Prebuilt/components/PreviousRoleInMetadata.tsx
- packages/roomkit-react/src/Prebuilt/components/RaiseHand.tsx
- packages/roomkit-react/src/Prebuilt/components/RoleChangeRequest/RoleChangeRequestModal.tsx
- packages/roomkit-react/src/Prebuilt/components/hooks/useMetadata.jsx
- yarn.lock
Reverts 100mslive/web-sdks#2715
> Revert "feat: hand raise config"

- packages/roomkit-react/package.json
- yarn.lock
> feat: upgrade noise cancellation

- packages/roomkit-react/src/Stats/Stats.tsx
> feat: add pause/freeze duration to tile SFN

- packages/hms-video-store/src/utils/constants.ts
> fix: update protocol spec version

- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
- packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx
> fix: scroll to latest chat message

- packages/roomkit-react/src/Prebuilt/components/Chat/ChatSelector.tsx
- packages/roomkit-react/src/Prebuilt/components/Connection/ConnectionIndicator.tsx
- packages/roomkit-react/src/Prebuilt/components/Footer/ParticipantList.tsx
> fix: remove connection indicator for sip, remove from chat selector

- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
- packages/roomkit-react/src/Prebuilt/components/hooks/useAutoEnableNoiseCancellation.tsx
> feat: auto enable noise cancellation

- packages/hms-video-store/src/notification-manager/managers/WhiteboardManager.ts
- packages/roomkit-react/src/Prebuilt/components/Footer/WhiteboardToggle.tsx
- packages/roomkit-react/src/Prebuilt/components/hooks/useCloseScreenshareWhiteboard.tsx
> fix: disable whiteboard on screenshare, prevent missing properties 

- packages/hms-video-store/src/interfaces/session-store/whiteboard.ts
- packages/hms-video-store/src/notification-manager/managers/WhiteboardManager.ts
- packages/hms-video-store/src/session-store/interactivity-center/HMSWhiteboardCenter.ts
- packages/hms-video-store/src/utils/constants.ts
- packages/hms-video-store/src/utils/whiteboard.ts
- packages/react-sdk/src/hooks/useWhiteboard.ts
> fix: move whiteboard url construction into core sdk

- packages/hms-video-store/src/session-store/interactivity-center/HMSWhiteboardCenter.ts
> fix: open whiteboard only if there are permissions

- examples/prebuilt-react-integration/src/App.jsx
- packages/hms-video-store/src/session-store/interactivity-center/HMSWhiteboardCenter.ts
> fix: whiteboard state on role change

- packages/roomkit-react/src/Modal/DialogContent.tsx
- packages/roomkit-react/src/Prebuilt/components/Footer/Footer.tsx
- packages/roomkit-react/src/Prebuilt/components/RoleChangeRequest/RequestPrompt.tsx
- packages/roomkit-react/src/Prebuilt/components/ScreenShareToggle.jsx
> fix: screenshare getting hidden, add scroll to dialog

- packages/hms-video-store/src/analytics/stats/BaseStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/PublishStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/SubscribeStatsAnalytics.ts
- packages/hms-video-store/src/analytics/stats/interfaces.ts
- packages/hms-video-store/src/media/tracks/HMSRemoteVideoTrack.ts
> feat: expected frame width/height from simulcast layer in subscriber.stats

- packages/roomkit-react/src/Stats/useQoE.ts
> fix: qoe for screenshare(video only tiles)

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
> fix: mweb speaker selection

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/signal/jsonrpc/index.ts
- packages/roomkit-react/src/Prebuilt/plugins/FlyingEmoji.jsx
- packages/roomkit-react/src/Stats/Stats.tsx
- packages/roomkit-react/src/Stats/useQoE.ts
> Release PR

- packages/roomkit-react/src/Prebuilt/components/SecondaryTiles.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ScreenshareLayout.tsx
> fix: final peer leaving the page breaks screenshare layout

- packages/hms-video-store/src/notification-manager/managers/WhiteboardManager.ts
- packages/react-sdk/src/hooks/useWhiteboard.ts
> fix: whiteboard role change from hls-viewer

- packages/roomkit-react/src/Prebuilt/components/RoleChangeModal.tsx
https://100ms.atlassian.net/browse/WEB-2807
> fix: add missing portal

- packages/hms-whiteboard/src/hooks/StoreClient.ts
- packages/hms-whiteboard/src/index.css
> fix: whiteboard initialisation, ui overlay issues

- packages/hms-whiteboard/src/Whiteboard.tsx
- packages/hms-whiteboard/src/hooks/StoreClient.ts
- packages/hms-whiteboard/src/hooks/useCollaboration.ts
- packages/hms-whiteboard/src/hooks/useSetEditorPermissions.tsx
> fix: close whiteboard

- packages/hms-whiteboard/src/hooks/useCollaboration.ts
- packages/hms-whiteboard/src/utils.ts
> fix: whiteboard role change/reopen by adding delay to reopen whiteboard

- examples/prebuilt-react-integration/src/App.jsx
- packages/hms-whiteboard/src/hooks/StoreClient.ts
- packages/hms-whiteboard/src/hooks/useCollaboration.ts
- packages/hms-whiteboard/src/hooks/useSetEditorPermissions.tsx
- packages/hms-whiteboard/src/utils.ts
> fix: use delay instead of count to wait for initial whiteboard records

- packages/hms-video-store/src/IHMSActions.ts
- packages/hms-video-store/src/notification-manager/HMSNotifications.ts
- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/signal/interfaces/responses.ts
- packages/hms-video-store/src/signal/interfaces/superpowers.ts
- packages/hms-video-store/src/signal/jsonrpc/index.ts
- packages/hms-video-store/src/signal/jsonrpc/models.ts
> feat: add `findPeerByName` API for large rooms

- packages/hms-video-store/src/sdk/index.ts
> fix: remove unnecesary validation for findPeerByName

- packages/roomkit-react/src/Prebuilt/components/MoreSettings/CaptionContent.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/TranscriptionNotifications.tsx
> refactor: transcription notifications

- scripts/build-webapp.js
> fix: build target to es6 for roomkit-react

- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
- packages/hms-virtual-background/src/constants.ts
https://100ms.atlassian.net/browse/WEB-2854
https://100ms.atlassian.net/browse/WEB-2855
> fix: bump effects version, add resolution change callback

- packages/roomkit-react/src/Prebuilt/components/Streaming/Common.jsx
> fix: poll header alignment

- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
> fix: update effects plugin implementation

- packages/hms-video-store/src/media/tracks/HMSVideoTrack.ts
- packages/hms-virtual-background/src/HMSEffectsPlugin.ts
> fix: mweb VB scenarios

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/GridLayout.tsx
> Merge main and resolve conflicts

- packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx
> fix: limit chat message length

- examples/prebuilt-react-integration/src/main.css
- packages/hms-video-store/src/diagnostics/ConnectivityCheck.ts
- packages/hms-video-store/src/diagnostics/HMSDiagnostics.ts
- packages/hms-video-store/src/diagnostics/interfaces.ts
- packages/roomkit-react/src/Diagnostics/BrowserTest.tsx
- packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
- packages/roomkit-react/src/Diagnostics/components.tsx
> fix: pre call diagnostics ui issues

- packages/roomkit-react/src/Prebuilt/App.tsx
> fix: remove diagnostics initialisation from prebuilt

- packages/roomkit-react/src/Diagnostics/AudioTest.tsx
- packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
- packages/roomkit-react/src/Diagnostics/components.tsx
https://100ms.atlassian.net/browse/WEB-2884 (Connection quality completion state)
https://100ms.atlassian.net/browse/WEB-2887 (Output selection for Safari)
https://100ms.atlassian.net/browse/WEB-2891 (Update audio test UI)
https://100ms.atlassian.net/browse/WEB-2893 (Output selection for mweb)
Going back to in progress if the test is run again and on completion, the state is updated
> fix: completion state for connectivity test, audio test ui

- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
- packages/roomkit-react/src/Diagnostics/VideoTest.tsx
- packages/roomkit-react/src/Diagnostics/components.tsx
https://100ms.atlassian.net/browse/WEB-2897
https://100ms.atlassian.net/browse/WEB-2883
> fix: diagnostics ui

- packages/hms-video-store/src/diagnostics/DiagnosticsStatsCollector.ts
- packages/hms-video-store/src/diagnostics/HMSDiagnostics.ts
- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
> fix: audio/video failing randomly due to stats mismatch in diagnostics

- packages/hms-video-store/src/sdk/index.ts
> fix: add peerId in leave logs

- packages/hms-video-store/src/sdk/LocalTrackManager.ts
- packages/hms-video-store/src/sdk/index.ts
> refactor: listener check, localtrackmanager constructor

- packages/hms-video-store/src/signal/jsonrpc/index.ts
- packages/hms-video-store/src/transport/index.ts
> fix: handle role change when offline -> online transition

- packages/roomkit-react/src/Diagnostics/AudioTest.tsx
- packages/roomkit-react/src/Diagnostics/BrowserTest.tsx
- packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
- packages/roomkit-react/src/Diagnostics/DiagnosticsContext.ts
- packages/roomkit-react/src/Diagnostics/VideoTest.tsx
- packages/roomkit-react/src/Diagnostics/components.tsx
> feat: add step-wise error, completed state in diagnostics

- packages/roomkit-react/src/Diagnostics/ConnectivityTest.tsx
- packages/roomkit-react/src/Diagnostics/Diagnostics.tsx
> fix: footer cropping on scroll in diagnostics result

- packages/hms-video-store/src/transport/index.ts
> revert: use callback flow for transport

- packages/hms-whiteboard/src/ErrorFallback.tsx
- packages/hms-whiteboard/src/Whiteboard.tsx
> fix: refresh whiteboard

- packages/roomkit-react/src/Prebuilt/components/Header/HeaderComponents.jsx
> fix: active speaker font size

- packages/roomkit-react/src/Prebuilt/App.tsx
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/MoreSettings.tsx
- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx
- packages/roomkit-react/src/Prebuilt/components/PIP/PIPChat.tsx
- packages/roomkit-react/src/Prebuilt/components/PIP/PIPWindow.tsx
- packages/roomkit-react/src/Prebuilt/components/PIP/usePIPChat.tsx
Close original chat window when opening pop out chat  
Pop out chat should be open with latest message in view  
Add “To XYZ” for DMs  
Align textarea placeholder vertically  
Overscroll shows white background  
Verify block and paused states
https://100ms.atlassian.net/browse/WEB-2935
> fix: pop out chat fixes

- packages/react-sdk/src/hooks/useAwayNotifications.ts
> fix: notification permission showing up on beam

- packages/react-sdk/src/hooks/useAwayNotifications.ts
> fix: unsubscribe after notification requested

- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-video-store/src/utils/track.ts
- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
> fix: audio not audible, blank tile when there is error on device selection

- .github/workflows/lint-test-build.yml
> ci: add merge group to workflow

- packages/hms-video-store/src/utils/track-audio-level-monitor.ts
- packages/react-sdk/src/hooks/useAwayNotifications.ts
- Audio level algorithm from official MDN docs - https://github.com/mdn/dom-examples/tree/main/media/web-dictaphone
-
> fix: audio silence detection

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
> fix: pick bt device on first load, select non-default version of default device

- packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
- packages/hms-video-store/src/device-manager/DeviceManager.ts
> fix: honour manual device selection on polling

- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
> fix: flicker on visibility change on desktop

- examples/prebuilt-react-integration/src/App.jsx
- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
> fix: add krisp plugin only when enabled for room

- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-video-store/src/transport/index.ts
> fix: restrict visibility handling to mweb

- packages/hms-video-store/src/transport/index.ts
> fix: handle errors on migration

- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
> fix: mweb tile getting blank when joined from 2 tabs

- packages/hms-video-store/src/sdk/index.ts
> fix: null check on event bus

- packages/hms-video-store/src/connection/HMSConnection.ts
- packages/hms-video-store/src/transport/index.ts
> fix: make sfu_node_id optional in offer

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-video-store/src/connection/HMSConnection.ts
- packages/hms-video-store/src/transport/index.ts
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-react/src/Prebuilt/components/AppData/AppData.tsx
- packages/roomkit-web/package.json
> Release - 0.12.18

- packages/roomkit-react/src/Prebuilt/App.tsx
- packages/roomkit-react/src/Prebuilt/AppStateContext.tsx
- packages/roomkit-react/src/Prebuilt/components/AuthToken.jsx
- packages/roomkit-react/src/Prebuilt/components/AuthToken.tsx
> fix: clear authToken on leave

- packages/roomkit-react/src/Prebuilt/components/PIP/PIPChat.tsx
> fix: pip chat copy

- .github/workflows/create-release-pr.yml
- .github/workflows/publish.yml
> ci: use dropdown for workflow manual trigger

- .github/workflows/generate-docs.yml
- .github/workflows/publish.yml
> ci: run api reference on latest publish

- packages/hms-video-store/src/media/tracks/HMSVideoTrack.ts
- packages/hms-video-store/src/utils/support.ts
- packages/roomkit-react/src/Video/Video.tsx
> fix: set autoplay in SDK to avoid play/pause overlay in apple low power mode

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/RoleProminence.tsx
> fix: tiles not rendering due in role prominence layout

- packages/hms-virtual-background/package.json
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
- scripts/build.js
> fix: update build paths for vb

- packages/hms-virtual-background/package.json
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBHandler.tsx
> fix: use import without destructuring

- packages/roomkit-react/src/Prebuilt/components/PIP/PIPChat.tsx
Fix chat copy for pop out chat when send permission is absent
> fix: chat copy

- packages/hms-video-store/src/utils/support.ts
> fix: fix isSafari check for mobile safari

- packages/roomkit-react/src/Prebuilt/AppStateContext.tsx
> fix: rejoin on end session

- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
- packages/roomkit-react/src/Prebuilt/components/Notifications/TrackUnmuteModal.tsx
- packages/roomkit-react/src/Prebuilt/components/ScreenshareTile.tsx
- packages/roomkit-react/src/Prebuilt/components/Settings/SettingsModal.jsx
- packages/roomkit-react/src/Prebuilt/components/TileMenu/TileMenu.tsx
- packages/roomkit-react/src/Prebuilt/components/TileMenu/TileMenuContent.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoTile.tsx
- packages/roomkit-react/src/Prebuilt/components/peerTileUtils.tsx
> feat: mweb enhancements

- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
> fix: avatar when coming from background

- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/utils/validations.ts
> feat: apply policy settings tracks added via addTrack

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
- yarn.lock
> Release - 0.12.20

- packages/hms-video-store/src/device-manager/DeviceManager.ts
- packages/hms-video-store/src/index.ts
- packages/hms-video-store/src/utils/media.ts
- packages/roomkit-react/src/Prebuilt/components/Header/common.jsx
> fix: device label categorisation on prebuilt

- packages/hms-video-store/src/media/tracks/HMSRemoteVideoTrack.ts
> fix: don't send none layer request for degradation

- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/EqualProminence.tsx
> revert: message update when no tiles

- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBOption.tsx
- packages/roomkit-react/src/Prebuilt/components/VirtualBackground/VBPicker.tsx
Attached is the video after the fix
https://github.com/user-attachments/assets/05f94f5a-7489-474d-b018-dfada24c540f
> fix: wrong color applied for vb selection in mweb

- packages/roomkit-react/package.json
- packages/roomkit-react/src/Avatar/Avatar.tsx
- packages/roomkit-react/src/Popover/Popover.stories.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/ProminenceLayout.tsx
- yarn.lock
> feat: upgrade stitches version to 1.3.1-1

- packages/react-sdk/src/hooks/useAwayNotifications.ts
> fix: notification api support check

- packages/roomkit-react/src/Prebuilt/components/Notifications/DeviceInUseError.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/DeviceInUseModal.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx
> fix: device in use error modal

- packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/PeerNotifications.tsx
- packages/roomkit-react/src/Prebuilt/components/Notifications/RoleChangeNotification.tsx
- fix: WEB-3034 made role change an independent component
> fix: make role change notification an independent component

- packages/hms-video-store/src/device-manager/DeviceManager.ts
> fix: device category check

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-video-store/src/device-manager/DeviceManager.ts
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> Release - 0.12.23

- packages/hms-video-store/src/transport/RetryScheduler.ts
> fix: handle terminal error thrown from retrying first error

- packages/hms-video-store/src/transport/RetryScheduler.ts
> fix: handle terminal while retrying in RetryScheduler

- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx
- packages/roomkit-react/src/Prebuilt/components/StatsForNerds.jsx
> fix: add new stats for nerds sheet

- packages/roomkit-react/src/Prebuilt/components/HMSVideo/HMSVideo.jsx
- packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
> fix: chat not shown for hls viewer

- packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/DesktopOptions.tsx
- packages/roomkit-react/src/Tooltip/Tooltip.tsx
- event propogation is causing this bubble to happen, stop it after event triggered is bubbled and problem will be solved ;
- 
similar to :  https://github.com/radix-ui/primitives/issues/2248
-
> fix: tooltip not getting dismissed 

- packages/hms-video-store/src/media/tracks/HMSVideoTrack.ts
> fix: local video replay after incoming call

- packages/hms-video-store/src/interfaces/preview-listener.ts
- packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
> fix: mute audio when device change throws an error in preview

- packages/roomkit-react/src/Prebuilt/components/EndCallFeedback/ThankyouView.tsx
- WEB-3052: Add cross button to Top Right to dismiss the ThankYou view
> fix: added cross button to dismiss the ThankYou view

- packages/roomkit-react/src/Prebuilt/AppStateContext.tsx
> fix: handle UI state on peer join timeout

- .github/CODEOWNERS
- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
- .github/workflows/alpha-release.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/cypress.yml
- .github/workflows/firstinteraction.yml
- .github/workflows/generate-docs.yml
- .github/workflows/lint-test-build.yml
- .github/workflows/publish.yml
- .github/workflows/stale.yml
- .github/workflows/sync-alpha-to-main.yml
- Added & updated Github actions
> ci: update github actions versions

- README.md
- examples/prebuilt-react-integration/README.md
- packages/hms-whiteboard/src/ErrorFallback.tsx
- packages/roomkit-react/README.md
- packages/roomkit-react/src/Prebuilt/components/AuthToken.tsx
- packages/roomkit-react/src/Prebuilt/components/ErrorBoundary.jsx
> fix: remove discord links

- packages/roomkit-react/src/Layout/Flex.tsx
- fix: corrected typo in Flex component
> fix: corrected typo in Flex component

- .github/CODEOWNERS
- README.md
- packages/hls-player/README.md
- packages/hls-player/package.json
- packages/hms-virtual-background/README.md
- packages/hms-whiteboard/README.md
- packages/hms-whiteboard/package.json
> docs: updated ReadMe

- README.md
- packages/hls-player/README.md
- packages/hls-stats/README.md
- packages/hms-video-store/README.md
- packages/hms-virtual-background/README.md
- packages/hms-whiteboard/README.md
- packages/react-icons/README.md
- packages/react-sdk/README.md
- packages/roomkit-react/README.md
- packages/roomkit-web/README.md
- docs: added meta badges on ReadMe
> docs: added meta badges on ReadMe

- package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- yarn.lock
> fix: dependabot errors

- packages/roomkit-react/package.json
- packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
- packages/roomkit-react/src/Prebuilt/components/VideoLayouts/Grid.tsx
- packages/roomkit-react/src/VideoTile/StyledVideoTile.tsx
- yarn.lock
Removing framer motion and noise cancellation due to severe performance issues on ios mweb
---
> revert: remove framer motion and nc for ios

- examples/prebuilt-react-integration/package.json
- yarn.lock
- Upgraded vite version to 5.4.11
- Diff: https://github.com/vitejs/vite/compare/v5.0.8...v5.4.11
> fix: upgraded vite version to 5.4.11

- packages/roomkit-react/package.json
- yarn.lock
Reverting krisp package update
> revert: krisp update

- packages/roomkit-react/package.json
- yarn.lock
> revert: krisp update (#3404) 

- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/signal/jsonrpc/index.ts
- packages/hms-video-store/src/transport/index.ts
- packages/hms-video-store/src/utils/constants.ts
> fix: send user or sdk request in reason for leave

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-video-store/src/device-manager/DeviceManager.ts
- packages/hms-video-store/src/events/EventBus.ts
- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-video-store/src/sdk/index.ts
- packages/hms-video-store/src/utils/constants.ts
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> Release - 0.12.28

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
- packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- packages/hms-video-store/src/utils/constants.ts
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> Release - 0.12.29

- packages/hms-video-store/src/sdk/index.ts
> fix: remove autoplay handling in join

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-video-store/src/utils/constants.ts
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> Release - 0.12.30

- packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts
> fix: retry audio track on unmute

- packages/hms-video-store/src/controller/beam/BeamSpeakerLabelsLogger.ts
> fix: add more logs for speakerlabellogging

- packages/hms-video-store/src/sdk/index.ts
- packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx
> fix: delay in device auto selection on mweb

- packages/hms-video-store/src/diagnostics/ConnectivityCheck.ts
- packages/hms-video-store/src/diagnostics/HMSDiagnostics.ts
- packages/hms-video-store/src/diagnostics/interfaces.ts
> feat: make duration of connectivity test customisable

- packages/roomkit-react/src/Prebuilt/plugins/CaptionsViewer.tsx
> fix(prebuilt): caption text should be visible

- packages/hms-video-store/src/media/settings/HMSAudioTrackSettings.ts
- packages/hms-video-store/src/media/settings/constants.ts
- packages/hms-video-store/src/plugins/audio/HMSAudioPluginsManager.ts
> fix: remove extra constraints applied for nc plugin

- packages/hls-player/src/controllers/HMSHLSPlayer.ts
> feat: improve hls url check

- packages/hms-video-store/src/utils/track.ts
> fix: handle permission query errors

- packages/react-sdk/package.json
- yarn.lock
> Allow react 19

- examples/prebuilt-react-integration/package.json
- packages/hls-player/package.json
- packages/hls-stats/package.json
- packages/hms-video-store/package.json
- packages/hms-virtual-background/package.json
- packages/hms-whiteboard/package.json
- packages/react-icons/package.json
- packages/react-sdk/package.json
- packages/roomkit-react/package.json
- packages/roomkit-web/package.json
> ci: update versions for release

- packages/roomkit-react/src/Prebuilt/components/Polls/Voting/useQuizSummary.tsx
> fix: increase leaderboard limit to 200
