packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-virtual-background/src/HMSEffectsPlugin.ts
- Currently changing the video input results in black tile if virtual background plugins are applied since the plugin has the older stream ID
- The fix processes the plugins when the device changes
- Tested on OBS virtual camera, to test on a real device
=> fix: process plugins on device change

packages/roomkit-react/src/Prebuilt/components/Preview/PreviewJoin.tsx
<details open>
<summary><a href="https://100ms.atlassian.net/browse/WEB-2485" title="WEB-2485" target="_blank">WEB-2485</a></summary>
<br />
<table>
<tr>
<th>Summary</th>
<td>Fix preview for smaller viewport resolutions</td>
</tr>
<tr>
<th>Type</th>
<td>
Incident
</td>
</tr>
<tr>
<th>Status</th>
<td>In Progress</td>
</tr>
<tr>
<th>Points</th>
<td>N/A</td>
</tr>
<tr>
<th>Labels</th>
<td>-</td>
</tr>
</table>
</details>
---
-
-
=> fix: preview scroll in smaller dimensions

packages/roomkit-react/src/Prebuilt/components/Polls/Voting/QuestionCard.jsx
- The indicator for correct/incorrect response was being shown on voting, before the quiz ended
After:
=> fix: hide incorrect answer indicator until quiz ends

packages/roomkit-react/src/Prebuilt/components/Polls/Voting/LeaderboardEntry.tsx, packages/roomkit-react/src/Prebuilt/components/Polls/Voting/PeerParticipationSummary.tsx, packages/roomkit-react/src/Prebuilt/components/Polls/common/utils.ts
- Format time into minutes and seconds, fix decimal places to match designs
=> fix: quiz duration formatting

packages/roomkit-react/src/Prebuilt/components/Chat/ChatBody.tsx, packages/roomkit-react/src/Prebuilt/components/Chat/EmptyChat.tsx
- The empty chat image is hidden for small screens https://100ms.atlassian.net/browse/WEB-2612
=> fix: improve chat UX for small heights

packages/roomkit-react/src/Prebuilt/components/Polls/Voting/LeaderboardEntry.tsx
=> fix: show trophy only if peer has a score

packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- For mweb, the video should be toggled off if the peer minimises the browser or switches tabs
=> feat: disable video when in background

packages/hms-video-store/src/analytics/stats/BaseStatsAnalytics.ts, packages/hms-video-store/src/analytics/stats/SubscribeStatsAnalytics.ts, packages/hms-video-store/src/analytics/stats/interfaces.ts, packages/hms-video-store/src/interfaces/webrtc-stats.ts, packages/hms-video-store/src/rtc-stats/utils.ts, packages/hms-video-store/src/utils/constants.ts
=> feat: add subscriber video stats to analytics

packages/roomkit-react/src/Button/Button.tsx, packages/roomkit-react/src/Fieldset/Fieldset.tsx, packages/roomkit-react/src/Input/PasswordInput.stories.tsx, packages/roomkit-react/src/Pagination/StyledPagination.stories.tsx, packages/roomkit-react/src/Prebuilt/IconButton.tsx, packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx, packages/roomkit-react/src/Prebuilt/components/EmojiReaction.jsx, packages/roomkit-react/src/Prebuilt/components/IconButtonWithOptions/IconButtonWithOptions.tsx, packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx, packages/roomkit-react/src/Prebuilt/components/Polls/common/OptionInputWithDelete.tsx, packages/roomkit-react/src/Prebuilt/components/RaiseHand.tsx, packages/roomkit-react/src/Prebuilt/components/pdfAnnotator/shareScreenOptions.jsx, packages/roomkit-react/src/Prebuilt/components/pdfAnnotator/uploadedFile.jsx, packages/roomkit-react/src/Prebuilt/primitives/DialogContent.jsx
=> fix: actions buttons bg for streaming, transparent color

packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx, packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx, packages/roomkit-react/src/Prebuilt/components/EmojiReaction.jsx
=> fix: show emoji reaction when chat paused

packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx, packages/roomkit-react/src/Prebuilt/components/Chat/ChatFooter.tsx, packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx, packages/roomkit-react/src/Prebuilt/components/EmojiReaction.jsx, packages/roomkit-react/src/Prebuilt/components/Footer/RoleOptions.tsx, packages/roomkit-react/src/Prebuilt/components/HMSVideo/HMSVideo.jsx, packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx, packages/roomkit-react/src/Prebuilt/components/MwebLandscapePrompt.tsx, packages/roomkit-react/src/Prebuilt/components/SidePaneTabs.tsx, packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx, packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx, packages/roomkit-react/src/Prebuilt/layouts/VideoStreamingSection.tsx
=> fix: hls layout for mweb

packages/roomkit-react/src/Prebuilt/components/AppData/useSidepane.js, packages/roomkit-react/src/Prebuilt/components/Footer/RoleOptions.tsx, packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
=> fix: stream reloading on polls change

packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx, packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
=> fix: chat showing even when disabled on role change

packages/roomkit-react/src/Prebuilt/components/Footer/ParticipantList.tsx, packages/roomkit-react/src/Prebuilt/components/Footer/RoleAccordion.tsx, packages/roomkit-react/src/Prebuilt/components/hooks/useGroupOnStageActions.tsx, packages/roomkit-react/src/Prebuilt/components/hooks/usePeerOnStageActions.tsx
=> feat: lower hand raise, bring to stage in hand raised accordion

packages/roomkit-react/src/Prebuilt/common/utils.js, packages/roomkit-react/src/Prebuilt/components/Polls/common/MultipleChoiceOptions.jsx, packages/roomkit-react/src/Prebuilt/components/Polls/common/OptionInputWithDelete.tsx, packages/roomkit-react/src/Prebuilt/components/Polls/common/SingleChoiceOptions.jsx
- Spacing parity between checkbox - option and radio - option
- Radio/checkbox shrinkage when the option is large
- Max limit for option input
=> fix: radio/checkbox shrink for longer options

packages/hms-video-store/src/device-manager/DeviceManager.ts
-  Chrome getusermedia returns a different device than what is set from the site settings from chrome settings. Hence this additional handling is needed to update to the correct deviceId.
- https://100ms.atlassian.net/browse/WEB-2797
=> fix: browser default camera/microphone not getting picked up

packages/hms-whiteboard/package.json
=> fix: remove `type: module` from whiteboard

examples/prebuilt-react-integration/src/App.jsx, packages/hms-video-store/src/session-store/interactivity-center/HMSWhiteboardCenter.ts, packages/hms-whiteboard/src/hooks/StoreClient.ts, packages/hms-whiteboard/src/hooks/useCollaboration.ts
=> fix: whiteboard flicker by syncing instance state only on page change

packages/roomkit-react/src/Prebuilt/components/Chat/ChatBody.tsx
=> fix: width for message sender name

packages/hms-video-store/src/plugins/audio/HMSAudioPluginsManager.ts, packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx
=> feat: add processed audio track only when plugin is added

packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/HandRaisedNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Preview/PreviewJoin.tsx, packages/roomkit-react/src/Prebuilt/components/Toast/ToastConfig.jsx
=> feat: hand raise browser notification when away from call

packages/roomkit-react/src/Prebuilt/components/AudioVideoToggle.tsx, packages/roomkit-react/src/Prebuilt/components/IconButtonWithOptions/IconButtonWithOptions.tsx
=> fix: move testid to buttons

examples/prebuilt-react-integration/src/App.jsx, packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-video-store/src/notification-manager/managers/TrackManager.ts, packages/hms-video-store/src/plugins/audio/HMSAudioPluginsManager.ts, packages/hms-video-store/src/plugins/video/HMSMediaStreamPluginsManager.ts, packages/hms-video-store/src/plugins/video/HMSVideoPluginsManager.ts, packages/hms-video-store/src/sdk/store/Store.ts, packages/hms-video-store/src/transport/index.ts
- Duplicate tiles on migration
- Screenshare not getting removed
- add audio/video plugins on migration
=> fix: sfu migration issues

packages/hms-video-store/src/signal/jsonrpc/index.ts, packages/hms-video-store/src/transport/index.ts
=> fix: update error, add node id to offer/answer/trickle

packages/hms-video-store/src/sdk/index.ts
Remove terminal error handling on preview after join 
-
-
=> fix: dont send preview failed after join on disconnect

packages/hms-video-store/src/transport/index.ts
=> fix: reconnection

packages/roomkit-react/src/Prebuilt/components/AppData/AppData.tsx
=> fix: separate no of tiles into a separate effect

examples/prebuilt-react-integration/src/App.jsx, packages/hls-player/src/controllers/HMSHLSPlayer.ts, packages/roomkit-react/src/Prebuilt/components/HMSVideo/HMSVideo.jsx, packages/roomkit-react/src/Prebuilt/layouts/HLSView.jsx
=> fix: make hls player take more space when in fullscreen

packages/hms-video-store/src/transport/RetryScheduler.ts, packages/hms-video-store/src/transport/index.ts, packages/hms-video-store/src/utils/constants.ts
=> fix: retry timeout of 60s for reconnection

.github/workflows/stale.yml
- Once a PR or Issue is older than 30 days, GitHub Actions will mark it as Stale for 10 days & then close it.
- Attached is a sample screenshot of the bot comment
=> ci: added github actions workflow to mark stale PRs & issues

packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
- Made native video track mute status change reason generic instead of always incoming-call
=> fix: make interruption reason generic 

packages/roomkit-react/src/Prebuilt/components/Notifications/DeviceChangeNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/ErrorNotificationModal.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/ErrorNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/MessageNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/PeerNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/PollNotificationModal.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/ReconnectNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/TrackBulkUnmuteModal.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/TrackNotifications.tsx, packages/roomkit-react/src/Prebuilt/components/Notifications/TrackUnmuteModal.tsx
- Fix: WEB-3030 refactored notifications component
=> refactor: Notifications in prebuilt

packages/hms-video-store/src/error/ErrorCodes.ts, packages/hms-video-store/src/error/ErrorFactory.ts, packages/hms-video-store/src/interfaces/config.ts, packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-video-store/src/media/tracks/HMSTrack.ts, packages/hms-video-store/src/media/tracks/HMSVideoTrack.ts, packages/hms-video-store/src/sdk/LocalTrackManager.test.ts, packages/hms-video-store/src/sdk/index.ts, packages/hms-video-store/src/utils/track-audio-level-monitor.ts
- Handle possible scenarios where this can be recovered
- Happens when whatsapp call is already happening and 100ms link is joined on iOS mweb.
=> fix: add an event when tracks are published with no data

packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-video-store/src/plugins/video/HMSMediaStreamPluginsManager.ts
=> fix: clean up mediastream plugins

packages/hms-video-store/src/device-manager/DeviceManager.ts, packages/hms-video-store/src/index.ts, packages/hms-video-store/src/utils/media.ts, packages/roomkit-react/src/Prebuilt/components/Header/common.jsx
1. Corrected typo in device label
2. Added checks for the currently selected audio output
3. Corrected check for device categories
=> fix: crash on publishing role to non-publishing role and back

packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts, packages/hms-video-store/src/events/EventBus.ts, packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-video-store/src/sdk/index.ts, packages/hms-video-store/src/utils/constants.ts, packages/roomkit-react/src/Prebuilt/components/Notifications/Notifications.tsx
=> fix: local video not recovering afer phone call, notifications

packages/roomkit-react/src/Prebuilt/layouts/WaitingView.tsx
=> fix: text size on waiting view on smaller screens

packages/roomkit-react/src/Prebuilt/App.tsx, packages/roomkit-react/src/Prebuilt/components/Chat/Chat.tsx, packages/roomkit-react/src/Prebuilt/components/VideoLayouts/GridLayout.tsx, packages/roomkit-react/src/Prebuilt/layouts/SidePane.tsx, packages/roomkit-react/src/Prebuilt/layouts/VideoStreamingSection.tsx
=> revert: lazy load

packages/roomkit-react/src/Prebuilt/components/Preview/PreviewJoin.tsx
Following the stitches upgrade, aspect ratio cannot be passed as a number
=> Fix: aspect ratio ignored due to type

packages/roomkit-react/src/Prebuilt/components/MoreSettings/SplitComponents/MwebOptions.tsx, packages/roomkit-react/src/Prebuilt/components/StatsForNerds.jsx
https://www.loom.com/share/08d6a0a429e547f29ed4bf72a40d1008?sid=21860cb7-fa3f-435d-8234-73a7adc5fcac
-
-
=> feat: add debug info in mweb stats for nerds

packages/hms-video-store/src/utils/media.ts
- Made device label change a warning instead of error
=> fix: make device label change a warning instead of error

packages/roomkit-react/src/Prebuilt/components/hooks/useTileLayout.tsx
- Fix: The tiles have a gap of 8px. The tile dim calculation does not account for this. The gaps should be subtracted from each tile's height and width depending on the number of rows and columns
=> fix: adjust tile dimension calculation to handle 480p recording

packages/roomkit-react/src/Prebuilt/components/InsetTile.tsx
- Local peer inset tile has incorrect aspect ratio on mweb for QA links
- This issue is due to stitches upgrade which requires that `aspectRatio` should be passed as a `string`
=> fix: local peer Inset tile incorrect aspect ratio on mweb

packages/hms-video-store/src/IHMSActions.ts, packages/hms-video-store/src/reactive-store/HMSSDKActions.ts
Beam currently continues recording even when it is not able to subscribe to any peers. Recording gets marked as successful despite being blank. Adding this method so beam can identify this and terminate after a timeout if the check fails continuously. 
This should not cause regular flows to fail (RTMP IN - no peers needed to join, rooms where js bridge is disabled - won't be able to execute this)
https://app.devrev.ai/100ms/works/ISS-30657
Usage:
---
=> feat: internal method to check if recording should continue

packages/roomkit-react/package.json, packages/roomkit-react/src/Prebuilt/components/VideoLayouts/Grid.tsx, packages/roomkit-react/src/VideoTile/StyledVideoTile.tsx, yarn.lock
- Open chat/participant list when multiple tiles are present
- The issue is more noticeable when downsizing the screen
Prod gzip:
<br />
<br />
Deployment gzip:
<br />
=> fix: animate resize to prevent flickers

packages/roomkit-react/src/Prebuilt/components/ConferenceScreen.tsx
- For the next release
- Remove tap to toggle header and footer behaviour
- Mweb HLS stream - viewer roles (Should remain hidden, same behaviour as prod)
- Mweb conference and broadcaster roles (Should always be visible, no autohide)
=> fix: remove autohide controls for mweb

packages/roomkit-react/src/Prebuilt/components/PIP/PIPChat.tsx
PIP chat height is broken after Chrome version 131 update.
Before:
After:
https://app.devrev.ai/100ms/works/ISS-30692
---
=> fix: pip chat height

packages/hms-video-store/src/media/settings/HMSAudioTrackSettings.ts, packages/hms-video-store/src/media/settings/constants.ts, packages/hms-video-store/src/plugins/audio/HMSAudioPluginsManager.ts, packages/roomkit-react/package.json, yarn.lock
Disable noise suppression and auto gain control while enabling Krisp and re-enable when Krisp is being stopped. In hms-noise-cancellation's latest version (0.0.2-alpha.3), the model can be specified through the query param: 
?model=https://assets.100ms.live/krisp/2.0.0/models/model_16 (default)
Other possible values: _8 (mobile, lower quality and cpu usage), _32 (desktop, best quality but crashes on mweb)
https://app.devrev.ai/100ms/works/ISS-30666
---
=> fix: audio track constraints when krisp is enabled

packages/roomkit-react/src/Prebuilt/App.tsx
- imports now happen from react-sdk instead of hms-video-store
=> fix: updated imports in Prebuilt App

packages/hms-video-store/src/analytics/AnalyticsEventFactory.ts, packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts
=> fix: re-subscribe audio on decode error

packages/roomkit-react/src/Prebuilt/components/Polls/Voting/QuestionCard.jsx
- Mitigate correct voting count during disconnection
=> fix: disable voting when disconnected

packages/hms-video-store/src/audio-sink-manager/AudioSinkManager.ts, packages/hms-video-store/src/device-manager/DeviceManager.ts
=> fix: use retry for decode error

packages/hms-video-store/src/device-manager/DeviceManager.ts, packages/hms-video-store/src/events/EventBus.ts, packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts, packages/hms-video-store/src/sdk/index.ts, packages/hms-video-store/src/utils/constants.ts
=> fix: handle unhandled exceptions and send to app

packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/media/tracks/HMSLocalVideoTrack.ts
=> fix: video not publishing on sfu migration

packages/hms-virtual-background/src/HMSEffectsPlugin.ts
- Run the effects only when an effect(background or blur) is set.
- Stop the effects when removing effects(no effect)
---
-
=> fix: add optimisations to HMSEffects Plugin

examples/prebuilt-react-integration/package.json, examples/prebuilt-react-integration/vite.config.js, packages/hls-player/package.json, packages/hls-stats/package.json, packages/hms-video-store/package.json, packages/hms-video-store/src/device-manager/DeviceManager.ts, packages/hms-video-store/src/diagnostics/ConnectivityCheck.ts, packages/hms-video-store/src/diagnostics/HMSDiagnostics.ts, packages/hms-video-store/src/diagnostics/interfaces.ts, packages/hms-video-store/src/interfaces/devices.ts, packages/hms-video-store/src/media/tracks/HMSLocalAudioTrack.ts, packages/hms-video-store/src/reactive-store/HMSSDKActions.ts, packages/hms-video-store/src/sdk/index.ts, packages/hms-virtual-background/package.json, packages/hms-whiteboard/package.json, packages/react-icons/package.json, packages/react-sdk/package.json, packages/roomkit-react/package.json, packages/roomkit-react/src/Prebuilt/components/Settings/DeviceSettings.jsx, packages/roomkit-web/package.json
=> Release - 0.12.32

packages/hms-video-store/src/IHMSActions.ts, packages/hms-video-store/src/interfaces/hls-config.ts, packages/hms-video-store/src/interfaces/hms.ts, packages/hms-video-store/src/reactive-store/HMSSDKActions.ts, packages/hms-video-store/src/sdk/index.ts, packages/hms-video-store/src/signal/interfaces/superpowers.ts, packages/roomkit-react/src/Prebuilt/components/Leave/LeaveRoom.tsx
Added the option to send stop_reason while stopping HLS. Pending changes in biz and beam
=> feat: stop reason for hls stop

examples/prebuilt-react-integration/package.json, packages/hls-player/package.json, packages/hls-stats/package.json, packages/hms-video-store/package.json, packages/hms-video-store/src/utils/track.ts, packages/hms-virtual-background/package.json, packages/hms-whiteboard/package.json, packages/react-icons/package.json, packages/react-sdk/package.json, packages/roomkit-react/package.json, packages/roomkit-web/package.json
Modified getAudioTrack and getVideoTrack functions to use exact constraints when deviceId is specified. This ensures getUserMedia will use the specified device or fail, rather than falling back to a default device.
=> fix: use exact constraint for deviceId in getUserMedia calls
